# Generated by Django 3.2.7 on 2021-11-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0003_auto_20211117_2153'),
        ('microblogs', '0004_user_followers'),
    ]

    operations = [
    ]
